# Generated by Django 4.1.7 on 2023-03-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timezone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False)),
                ('time_zone', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
