# Generated by Django 4.1.7 on 2023-03-31 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timezone', '0002_inputdata_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InputData',
            new_name='TimeZone',
        ),
    ]
